name: Validate JSON

on:
  pull_request:
    branches: [ main, shinhwi ]
    paths:
      - '**.json'
  push:
    branches: [ main, shinhwi ]
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          pattern: '**/*.json'
