name: Validate JSON

on:
  pull_request:
    paths:
      - '*.json'
  push:
    branches:
      - main
      - shinhwi
    paths:
      - '*.json'

jobs:
  validate-dapps-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate dapps.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./dapps.json

  validate-nfts-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate nfts.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./nfts.json