name: Validate JSON Syntax

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.json'
  push:
    branches: [ main, shinhwi ]
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON syntax
        run: |
          find . -name "*.json" -type f -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            if jq empty "$file"; then
              echo "✅ $file is valid JSON"
            else
              echo "❌ $file is invalid JSON"
              exit 1
            fi
          done
